project:
  type: website

website:
  title: "ISSS608-Group12"
  navbar:
    left:
      - href: "GroupProject/proposal.html"
        text: "Proposal"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

