project:
  type: website

website:
  title: "ISSS608-Group12"
  navbar:
    left:
      - href: "GroupProject/Introduction.html"
        text: "Introduction"
      - href: "GroupProject/proposal.html"
        text: "Project Report"
      - href: "GroupProject/ShinyApp.html"
        text: "Shiny App"
      - href: "GroupProject/Poster.html"
        text: "Poster"   
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

