---
title: "EDA"
---

```{r}
pacman::p_load(ggthemes, readxl, knitr, ggplot2, ggrepel, ggiraph, plotly, ggh4x, patchwork, gganimate, hrbrthemes, ggExtra, reshape2, corrplot, tidyverse)
```

```{r}
loan <- read_xlsx("data/loan.xlsx")
```

```{r}
##Education, Employment
ggplot(loan, aes(x = Education, fill = good_bad_flag)) + 
  geom_bar(position = "dodge")
```

```{r}
loan <- loan %>%
  mutate(age_group = case_when(
    Age <= 30 ~ "0-30",
    Age <= 60 ~ "30-60",
    TRUE ~ "60+"
  )) %>% mutate(int_flag = ifelse(good_bad_flag == "Good", 1, 0))


ggplot(loan, aes(x = age_group, fill = good_bad_flag)) + 
  geom_bar(position = "dodge")
```

```{r}
corr <- cor(loan[, c("Loanamount", "Totaldue", "Termdays", "Total_bad", "Total_loan_number", "Default_ratio", "Total_due", "Total_loan", "Employment", "Education")])

melted_corr <- melt(corr)

ggplot(melted_corr, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "blue") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Correlation Heatmap")
```

```{r}
ggstatsplot::ggcorrmat(
  data = loan, 
  cor.vars = c("Loanamount", "Totaldue", "Termdays", "Total_bad", "Total_loan_number", "Default_ratio", "Total_due", "Total_loan", "Employment", "Education"),
  ggcorrplot.args = list(outline.color = "black", 
                         hc.order = TRUE,
                         tl.cex = 10),
  title    = "Correlogram for loan default dataset"
)
```

```{r}
p <- ggplot(loan, aes(x=Total_loan, y=Default_ratio, color=good_bad_flag)) +
      geom_point(aes(group = good_bad_flag)) +
      theme(legend.position="none")
p3 <- ggMarginal(p, type="density")
p3
```
