---
title: "EDA"
author: "Xu Jiajie"
---

```{r}
pacman::p_load(funModeling, dplyr, ggstatsplot,readr,ggplot2,lubricate,viridis,corrplot)
```

```{r}
Demographic <- read_csv("data/traindemographics.csv")
```

```{r}
summary(Demographic)
```

```{r}
Performance <- read_csv("data/trainperf.csv")
```

```{r}
merge_df <-merge(Demographic,Performance,by='customerid')
merge_df
```

```{r}
Previousloans <-read.csv("data/trainprevloans.csv")
```

```{r}
merge_df1 <-merge(Demographic,Previousloans,by='customerid')
```

```{r}
new_df <-merge_df1[,c("employment_status_clients","level_of_education_clients","loanamount","loannumber","termdays")]
```

```{r}
new_df$level_of_education_clients[is.na(new_df$level_of_education_clients)] <- "No submit"
```

```{r}
new_df$employment_status_clients[is.na(new_df$employment_status_clients)] <- "No submit"
```

```{r}
new_df <- transform(new_df, total_loan_amount = ave(loanamount, employment_status_clients, FUN = sum))
```

```{r}
merge_df <- merge_df %>%
  group_by(good_bad_flag) %>%
  mutate(total_loan_amount = sum(loanamount))
head(merge_df)
```

```{r}
ggplot(merge_df, aes(x = good_bad_flag, y = total_loan_amount, fill = good_bad_flag)) +
  geom_bar(stat = "identity") +
  xlab("Loan Performance") +
  ylab("Total Loan Amount") +
  ggtitle("Relationship between Loan Performance and Total Loan Amount")
```

```{r}
total_loan_amount <- aggregate(loanamount ~ level_of_education_clients, new_df, sum)
```

```{r}
ggplot(total_loan_amount, aes(x =level_of_education_clients , y = loanamount)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Education Level", y = "Total Loan Amount", title = "Total Loan Amount by Education Level")
```

```{r}
total_loan_amount1 <- aggregate(loanamount ~ employment_status_clients, new_df, sum)
```

```{r}
ggplot(total_loan_amount1, aes(x =employment_status_clients , y = loanamount)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "employment Level", y = "Total Loan Amount", title = "Total Loan Amount by employment Level")
```

```{r}
ggplot(merge_df, aes(x = good_bad_flag, y = loanamount, fill = good_bad_flag)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  labs(x = "Good/Bad Flag", y = "Loan Amount") +
  ggtitle("Box Plot of Loan Amount by Good/Bad Flag") +
  theme_classic()
```

```{r}
ggplot(data = new_df, aes(x =employment_status_clients , y = loanamount)) +
  geom_boxplot() +
  labs(x = "employment Level", y = "Loan Amount") +
  theme_minimal()
```

```{r}
ggplot(data = new_df, aes(x =level_of_education_clients , y = loanamount)) +
  geom_boxplot() +
  labs(x = "Education Level", y = "Loan Amount") +
  theme_minimal()
```

#explore the education and good_bad_flat and load amount

```{r}
ggplot(merge_df, aes(x =level_of_education_clients, y = loanamount, fill = good_bad_flag)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(x = "Education", y = "Loan Amount") +
  ggtitle("Stacked Bar Chart of Loan Amount by Education and Good/Bad Flag")
```

```{r}
ggplot(merge_df, aes(x =employment_status_clients, y = loanamount, fill = good_bad_flag)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(x = "Education", y = "Loan Amount") +
  ggtitle("Stacked Bar Chart of Loan Amount by Education and Good/Bad Flag")
```

```{r}
library(lubridate)
merge_df$age <- floor(as.numeric(interval(ymd(merge_df$birthdate), Sys.Date()) / years(1)))
head(merge_df)
```

```{r}
ggplot(merge_df, aes(x = age, y = loanamount, fill = level_of_education_clients)) +
  geom_col(position = "stack")
```

```{r}
ggplot(merge_df, aes(x = age, y = loanamount, fill = employment_status_clients)) +
  geom_col(position = "stack")
```

```{r}
str(merge_df)
```

```{r}
ggstatsplot::ggcorrmat(
  data =merge_df, 
  cor.vars = c("loanamount", "termdays", "loannumber", "totaldue"),
  ggcorrplot.args = list(outline.color = "black", 
                         hc.order = TRUE,
                         tl.cex = 10),
  title    = "Correlogram for loan default dataset"
)
```

```{r}
dim(merge_df)
```
