---
title: "final EDA"
---

```{r}
pacman::p_load(funModeling, dplyr, ggstatsplot,readr,ggplot2,lubricate,viridis,corrplot,reshape2)
```

```{r}
Demographic <- read_csv("data/traindemographics.csv")
```

```{r}
Previousloans <- read_csv("data/trainprevloans.csv")
```

```{r}
merged_AC <- merge(Demographic, Previousloans, by = "customerid")
merged_AC
```

```{r}
merged_AC$status <- ifelse(as.Date(merged_AC$firstrepaiddate) > as.Date(merged_AC$firstduedate), "overtime", "ontime")
```

```{r}
ggplot(merged_AC, aes(x = status, y = loanamount, fill = status)) +
  geom_bar(stat = "identity") +
  labs(title = "Relationship between Loan Status and Amount",
       x = "Status",
       y = "Total Loan Amount",
       fill = "Status")
```

```{r}
merged_AC <- merged_AC %>%
  mutate(age = interval(ymd(birthdate), Sys.Date()) %/% years(1))
```

#categorical columns exploring

```{r}
merged_AC <- merged_AC %>% 
  filter(status %in% c("ontime", "overtime")) 
```

```{r}
merged_AC_A <- merged_AC %>% 
  group_by(age, status) %>% 
  summarise(count = n())
```

```{r}
ggplot(merged_AC_A, aes(x = age, y = count, color = status)) +
  geom_point() +
  labs(color = "Status")
```

```{r}
ggplot(merged_AC, aes(x = age, y = loanamount, fill = level_of_education_clients)) +
  geom_col(position = "stack")
```

```{r}
ggplot(merged_AC, aes(x = age, y = loanamount, fill = employment_status_clients)) +
  geom_col(position = "stack")
```

```{r}
corr <- cor(merged_AC[, c("loanamount", "totaldue", "termdays", "loannumber")])
melted_corr <- melt(corr)

ggplot(melted_corr, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "blue") +
  geom_text(aes(label = round(value, 2)), size = 3) + # add this layer to show the correlation values
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = "", y = "") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Correlation Heatmap")
```

```{r}
install.packages('shiny')
```
