---
title: "Loan Default Prediction"
author: "Xu Jiajie"
---

```{r}
pacman::p_load(funModeling, dplyr, ggstatsplot,readr,ggplot2,lubricate)
```

```{r}
Demographic <- read_csv("data/traindemographics.csv")

```

```{r}
df_status(Demographic)
```

```{r}
summary(Demographic)
```

```{r}
Performance <- read_csv("data/trainperf.csv")
```

```{r}
merge_df <-merge(Demographic,Performance,by='customerid')
merge_df
```

```{r}
str(merge_df)
```

```{r}
is.na(merge_df)
```

```{r}
lapply(merge_df, is.null)
```

```{r}
nrow(merge_df)==0||ncol(merge_df)==0
```

```{r}
Previousloans <-read.csv("data/trainprevloans.csv")
```

```{r}
merge_df1 <-merge(Demographic,Previousloans,by='customerid')
```

```{r}
df_status(merge_df1)
```

```{r}
new_df <-merge_df1[,c("employment_status_clients","level_of_education_clients","loanamount","loannumber","termdays")]
```

```{r}
df_status(new_df)
```

```{r}
new_df$level_of_education_clients[is.na(new_df$level_of_education_clients)] <- "No submit"

```

```{r}
#new_df$level_of_education_clients[new_df$level_of_education_clients %in% c("Primary")] <- "1"

```

```{r}
#new_df$level_of_education_clients[new_df$level_of_education_clients %in% c("Secondary")] <- "2"
```

```{r}
#$level_of_education_clients[new_df$level_of_education_clients %in% c("Graduate")] <- "3"
```

```{r}
#new_df$level_of_education_clients[new_df$level_of_education_clients %in% c("Post-Graduate")] <- "4"
```

```{r}
new_df$employment_status_clients[is.na(new_df$employment_status_clients)] <- "No submit"
```

```{r}
#new_df$employment_status_clients[new_df$employment_status_clients %in% c("Retired")] <- "1"
```

```{r}
#new_df$employment_status_clients[new_df$employment_status_clients %in% c("Self-Employed")] <- "2"
```

```{r}
#new_df$employment_status_clients[new_df$employment_status_clients %in% c("Permanent")] <- "3"
```

```{r}
new_df
```

```{r}
#new_df_mx <-as.matrix(new_df)
```

```{r}
#df_status(new_df)
```

```{r}
#new_df$employment_status_clients <- as.integer(new_df$employment_status_clients)
```

```{r}
#new_df$level_of_education_clients <- as.integer(new_df$level_of_education_clients)
```

```{r}
#new_df
```

```{r}
#new_df_mx <- as.matrix(new_df)
```

```{r}
#heatmap(new_df_mx, Rowv=NA, Colv=NA, col = cm.colors(256), scale="none", margins=c(12, 8))
```

```{r}
new_df <- transform(new_df, total_loan_amount = ave(loanamount, employment_status_clients, FUN = sum))
```

```{r}
new_df
```

```{r}
total_loan_amount <- aggregate(loanamount ~ level_of_education_clients, new_df, sum)
```

```{r}
ggplot(total_loan_amount, aes(x =level_of_education_clients , y = loanamount)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Education Level", y = "Total Loan Amount", title = "Total Loan Amount by Education Level")
```

```{r}
total_loan_amount1 <- aggregate(loanamount ~ employment_status_clients, new_df, sum)
```

```{r}
ggplot(total_loan_amount1, aes(x =employment_status_clients , y = loanamount)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "employment Level", y = "Total Loan Amount", title = "Total Loan Amount by employment Level")
```

#Graduate and permanet

```{r}
ggplot(data = new_df, aes(x =employment_status_clients , y = loanamount)) +
  geom_boxplot() +
  labs(x = "employment Level", y = "Loan Amount") +
  theme_minimal()
  
```

```{r}
ggplot(data = new_df, aes(x =level_of_education_clients , y = loanamount)) +
  geom_boxplot() +
  labs(x = "Education Level", y = "Loan Amount") +
  theme_minimal()
```

#explore the age, education level and loan amount

```{r}
library(lubridate)
merge_df$age <- floor(as.numeric(interval(ymd(merge_df$birthdate), Sys.Date()) / years(1)))
head(merge_df)
```

```{r}
ggplot(merge_df, aes(x = age, y = loanamount, fill = level_of_education_clients)) +
  geom_col(position = "stack")
```

#explore the age, employment level and loan amount

```{r}
ggplot(merge_df, aes(x = age, y = loanamount, fill = employment_status_clients)) +
  geom_col(position = "stack")
```

#explore the totaldue and loadnumber

#explore the terms base on different education and employment

explore totaldue and terms' relationship for different education level
